/* This file is strictly intended for graphics imports*/

/*
    Index generation with python in 2 lines:
    for file in sorted(os.listdir('./')):
        print('export const arcd_{} = require(\'./arcade_pack/{}\')'.format(file.replace(" ", "_").replace("-", "_")[:-4], file))

*/

/* avatar_pack exports */
export const avtr_001_call_center_agent = require('./avatar_pack/001-call center agent.svg')
export const avtr_002_phone_operator = require('./avatar_pack/002-phone operator.svg')
export const avtr_003_call_center_agent = require('./avatar_pack/003-call center agent.svg')
export const avtr_004_call_center_agent = require('./avatar_pack/004-call center agent.svg')
export const avtr_005_call_center_agent = require('./avatar_pack/005-call center agent.svg')
export const avtr_006_call_center_agent = require('./avatar_pack/006-call center agent.svg')
export const avtr_007_phone_operator = require('./avatar_pack/007-phone operator.svg')
export const avtr_008_call_center_agent = require('./avatar_pack/008-call center agent.svg')
export const avtr_009_customer_service_agent = require('./avatar_pack/009-customer service agent.svg')
export const avtr_010_call_center_agent = require('./avatar_pack/010-call center agent.svg')
export const avtr_011_call_center_agent = require('./avatar_pack/011-call center agent.svg')
export const avtr_012_call_center_agent = require('./avatar_pack/012-call center agent.svg')
export const avtr_013_call_center_agent = require('./avatar_pack/013-call center agent.svg')
export const avtr_014_call_center_agent = require('./avatar_pack/014-call center agent.svg')
export const avtr_015_call_center_agent = require('./avatar_pack/015-call center agent.svg')
export const avtr_016_technical_Support = require('./avatar_pack/016-technical Support.svg')
export const avtr_017_call_center_agent = require('./avatar_pack/017-call center agent.svg')
export const avtr_018_call_center_agent = require('./avatar_pack/018-call center agent.svg')
export const avtr_019_call_center_agent = require('./avatar_pack/019-call center agent.svg')
export const avtr_020_call_center_agent = require('./avatar_pack/020-call center agent.svg')
export const avtr_021_call_center_agent = require('./avatar_pack/021-call center agent.svg')
export const avtr_022_call_center_agent = require('./avatar_pack/022-call center agent.svg')
export const avtr_023_call_center_agent = require('./avatar_pack/023-call center agent.svg')
export const avtr_024_call_center_agent = require('./avatar_pack/024-call center agent.svg')
export const avtr_025_call_center_agent = require('./avatar_pack/025-call center agent.svg')
export const avtr_026_call_center_agent = require('./avatar_pack/026-call center agent.svg')
export const avtr_027_call_center_agent = require('./avatar_pack/027-call center agent.svg')
export const avtr_028_call_center_agent = require('./avatar_pack/028-call center agent.svg')
export const avtr_029_call_center_agent = require('./avatar_pack/029-call center agent.svg')
export const avtr_030_call_center_agent = require('./avatar_pack/030-call center agent.svg')
export const avtr_031_call_center_agent = require('./avatar_pack/031-call center agent.svg')
export const avtr_032_call_center_agent = require('./avatar_pack/032-call center agent.svg')
export const avtr_033_call_center_agent = require('./avatar_pack/033-call center agent.svg')
export const avtr_034_call_center_agent = require('./avatar_pack/034-call center agent.svg')
export const avtr_035_call_center_agent = require('./avatar_pack/035-call center agent.svg')
export const avtr_036_call_center_agent = require('./avatar_pack/036-call center agent.svg')
export const avtr_037_call_center_agent = require('./avatar_pack/037-call center agent.svg')
export const avtr_038_call_center_agent = require('./avatar_pack/038-call center agent.svg')
export const avtr_039_call_center_agent = require('./avatar_pack/039-call center agent.svg')
export const avtr_040_call_center_agent = require('./avatar_pack/040-call center agent.svg')
export const avtr_041_call_center_agent = require('./avatar_pack/041-call center agent.svg')
export const avtr_042_call_center_agent = require('./avatar_pack/042-call center agent.svg')
export const avtr_043_call_center_agent = require('./avatar_pack/043-call center agent.svg')
export const avtr_044_call_center_agent = require('./avatar_pack/044-call center agent.svg')
export const avtr_045_call_center_agent = require('./avatar_pack/045-call center agent.svg')
export const avtr_046_call_center_agent = require('./avatar_pack/046-call center agent.svg')
export const avtr_047_call_center_agent = require('./avatar_pack/047-call center agent.svg')
export const avtr_048_call_center_agent = require('./avatar_pack/048-call center agent.svg')
export const avtr_049_call_center_agent = require('./avatar_pack/049-call center agent.svg')
export const avtr_050_call_center_agent = require('./avatar_pack/050-call center agent.svg')

/* arcade_pack exports */
export const arcd_001_shooting_game = require('./arcade_pack/001-shooting game.svg')
export const arcd_002_basketball = require('./arcade_pack/002-basketball.svg')
export const arcd_003_arcade = require('./arcade_pack/003-arcade.svg')
export const arcd_004_racing = require('./arcade_pack/004-racing.svg')
export const arcd_005_slot_machine = require('./arcade_pack/005-slot machine.svg')
export const arcd_006_cherry = require('./arcade_pack/006-cherry.svg')
export const arcd_007_life = require('./arcade_pack/007-life.svg')
export const arcd_008_you = require('./arcade_pack/008-you.svg')
export const arcd_009_arcade = require('./arcade_pack/009-arcade.svg')
export const arcd_010_arcade = require('./arcade_pack/010-arcade.svg')
export const arcd_011_dart = require('./arcade_pack/011-dart.svg')
export const arcd_012_star = require('./arcade_pack/012-star.svg')
export const arcd_013_bowling_pins = require('./arcade_pack/013-bowling pins.svg')
export const arcd_014_screen = require('./arcade_pack/014-screen.svg')
export const arcd_015_tokens = require('./arcade_pack/015-tokens.svg')
export const arcd_016_spaceship = require('./arcade_pack/016-spaceship.svg')
export const arcd_017_member_card = require('./arcade_pack/017-member card.svg')
export const arcd_018_pinball = require('./arcade_pack/018-pinball.svg')
export const arcd_019_strawberry = require('./arcade_pack/019-strawberry.svg')
export const arcd_020_play = require('./arcade_pack/020-play.svg')
export const arcd_021_token = require('./arcade_pack/021-token.svg')
export const arcd_022_air_hockey = require('./arcade_pack/022-air hockey.svg')
export const arcd_023_gamepad = require('./arcade_pack/023-gamepad.svg')
export const arcd_024_dancing_game = require('./arcade_pack/024-dancing game.svg')
export const arcd_025_karaoke = require('./arcade_pack/025-karaoke.svg')
export const arcd_026_whack_a_mole = require('./arcade_pack/026-whack a mole.svg')
export const arcd_027_arcade = require('./arcade_pack/027-arcade.svg')
export const arcd_028_vending_machine = require('./arcade_pack/028-vending machine.svg')
export const arcd_029_motorbike = require('./arcade_pack/029-motorbike.svg')
export const arcd_030_game_over = require('./arcade_pack/030-game over.svg')
export const arcd_031_billiard = require('./arcade_pack/031-billiard.svg')
export const arcd_032_joystick = require('./arcade_pack/032-joystick.svg')
export const arcd_033_heart = require('./arcade_pack/033-heart.svg')
export const arcd_034_bomb = require('./arcade_pack/034-bomb.svg')
export const arcd_035_ufo = require('./arcade_pack/035-ufo.svg')
export const arcd_036_punching_ball = require('./arcade_pack/036-punching ball.svg')
export const arcd_037_ticket_machine = require('./arcade_pack/037-ticket machine.svg')
export const arcd_038_crane_machine = require('./arcade_pack/038-crane machine.svg')
export const arcd_039_gamepad = require('./arcade_pack/039-gamepad.svg')
export const arcd_040_ping_pong = require('./arcade_pack/040-ping pong.svg')
export const arcd_041_cubes = require('./arcade_pack/041-cubes.svg')
export const arcd_042_arcade = require('./arcade_pack/042-arcade.svg')
export const arcd_043_bird = require('./arcade_pack/043-bird.svg')
export const arcd_044_fencing = require('./arcade_pack/044-fencing.svg')
export const arcd_045_tetris = require('./arcade_pack/045-tetris.svg')
export const arcd_046_cinema_tickets = require('./arcade_pack/046-cinema tickets.svg')
export const arcd_047_rotation = require('./arcade_pack/047-rotation.svg')
export const arcd_048_dart = require('./arcade_pack/048-dart.svg')
export const arcd_049_lottery_game = require('./arcade_pack/049-lottery game.svg')
export const arcd_050_table_football = require('./arcade_pack/050-table football.svg')

export const song_001_khalid_saturday_nights = require('./Saturday Nights - Khalid.mp3')